# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0efd18ceddf60d68289a243b56cd0bf21d8550a9daa4ec220d3bab1a5b12fd5e0b0049966beea5be70f4208a4e2eae004aeb021fb76f7361fcac060c8582febe

test:
  secret_key_base: 129e7141e75cb0632785ecc9edc39787e0f664fdcfc04e77c89dd31fdd8fa2539cf8ad527439aae4138c8526d38fc3104c6d6c1efe38d479b8a973b98d55dfa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
